# Generated by Django 5.1 on 2024-12-23 20:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='expereince',
            name='present',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expereince',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expereince',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
