# Generated by Django 5.1 on 2024-12-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_expereince_present_alter_expereince_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expereince',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
