# Generated by Django 5.1.1 on 2025-06-14 06:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_expereince_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expereince',
            name='description',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_detail',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='expereince',
            name='present',
            field=models.BooleanField(),
        ),
    ]
